services:
  app:
    build: . # 현재 디렉토리의 Dockerfile을 사용하여 애플리케이션 이미지 빌드
    ports:
      - '3000:3000' # 호스트의 3000 포트를 컨테이너의 3000 포트에 매핑
    environment:
      - NODE_ENV=production # 애플리케이션 환경 변수 설정 (프로덕션 모드)

  nginx:
    image: nginx:latest # 최신 nginx 이미지 사용
    ports:
      - '80:80' # 호스트의 80 포트를 컨테이너의 80 포트에 매핑 (웹 서버 접근용)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # 로컬 nginx 설정 파일을 컨테이너에 마운트
    depends_on:
      - app # app 서비스가 먼저 시작된 후에 nginx 서비스 시작
